# Generated by Django 5.0.14 on 2026-07-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("referrer_name", models.CharField(max_length=100)),
                ("referrer_phone", models.CharField(max_length=15)),
                ("referrer_email", models.EmailField(blank=True, max_length=254)),
                ("client_name", models.CharField(max_length=100)),
                ("client_phone", models.CharField(blank=True, max_length=15)),
                (
                    "deal_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "commission_paid",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("converted", "Converted"),
                            ("paid", "Commission Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_submissions",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Submission",
                "verbose_name_plural": "Referral Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
