# Generated by Django 5.0.14 on 2026-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("photo", models.ImageField(blank=True, upload_to="testimonials/")),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("review", models.TextField()),
                ("location", models.CharField(blank=True, max_length=100)),
                ("project", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
