# Generated by Django 5.0.14 on 2026-09-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(blank=True, upload_to="team/"),
        ),
    ]
