# Generated by Django 5.0.14 on 2026-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "commission_pct",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                ("image", models.ImageField(blank=True, upload_to="referral/")),
                ("steps", models.JSONField(blank=True, default=list)),
                ("faq", models.JSONField(blank=True, default=list)),
                ("button_text", models.CharField(default="Join Now", max_length=100)),
                ("button_link", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Referral Program",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=300)),
                ("long_description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="services/")),
                ("banner", models.ImageField(blank=True, upload_to="services/banners/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
