# Generated by Django 5.0.14 on 2026-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="CSS icon class ya icon name", max_length=100
                    ),
                ),
                ("banner_image", models.ImageField(blank=True, upload_to="services/banners/")),
                ("short_description", models.CharField(max_length=300)),
                ("long_description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_referral_enabled", models.BooleanField(default=False)),
                (
                    "referral_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("flat", "Flat Amount")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "referral_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Percentage (e.g. 50) ya flat amount (e.g. 10000)",
                        max_digits=10,
                    ),
                ),
                (
                    "referral_note",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Festival Offer", "Limited Time - ends Dec 31"',
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
