# Generated by Django 5.0.14 on 2026-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("inquiry_customer_confirmation", "Inquiry — User ko Confirmation"),
                            ("inquiry_admin_notification", "Inquiry — Admin ko Notification"),
                            (
                                "referral_customer_confirmation",
                                "Referral — Referrer ko Confirmation",
                            ),
                            ("referral_admin_notification", "Referral — Admin ko Notification"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("body_text", models.TextField()),
                (
                    "body_html",
                    models.TextField(
                        blank=True,
                        help_text="Optional HTML version. Blank rakho to body_text use hoga.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("site_name", models.CharField(default="Aai Bhavani Consultant", max_length=200)),
                ("site_tagline", models.CharField(blank=True, max_length=300)),
                ("logo", models.ImageField(blank=True, upload_to="site/")),
                ("favicon", models.ImageField(blank=True, upload_to="site/")),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("google_map_url", models.URLField(blank=True)),
                ("working_hours", models.CharField(blank=True, max_length=200)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_subtitle", models.CharField(blank=True, max_length=300)),
                ("hero_description", models.TextField(blank=True)),
                ("hero_image", models.ImageField(blank=True, upload_to="hero/")),
                ("hero_button_text", models.CharField(blank=True, max_length=100)),
                ("hero_button_link", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("inquiry_customer_confirmation", "Inquiry — User ko Confirmation"),
                            ("inquiry_admin_notification", "Inquiry — Admin ko Notification"),
                            (
                                "referral_customer_confirmation",
                                "Referral — Referrer ko Confirmation",
                            ),
                            ("referral_admin_notification", "Referral — Admin ko Notification"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("template_body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp Template",
                "verbose_name_plural": "WhatsApp Templates",
            },
        ),
    ]
