# Generated by Django 5.0.14 on 2026-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("youtube", "YouTube"),
                            ("reel", "Instagram Reel"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="gallery/")),
                ("video_url", models.URLField(blank=True)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("property", "Property"),
                            ("interior", "Interior"),
                            ("office", "Office"),
                            ("events", "Events"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
