# Generated by Django 5.0.14 on 2026-07-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("button_text", models.CharField(blank=True, max_length=100)),
                ("button_link", models.CharField(blank=True, max_length=200)),
                ("button_2_text", models.CharField(blank=True, max_length=100)),
                ("button_2_link", models.CharField(blank=True, max_length=200)),
                ("desktop_image", models.ImageField(blank=True, upload_to="hero/")),
                ("mobile_image", models.ImageField(blank=True, upload_to="hero/")),
                ("overlay_opacity", models.FloatField(default=0.5)),
                ("height", models.CharField(default="100vh", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Section",
            },
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("page", models.CharField(max_length=100, unique=True)),
                ("meta_title", models.CharField(max_length=160)),
                ("meta_description", models.TextField(max_length=320)),
                ("keywords", models.TextField(blank=True)),
                ("og_image", models.ImageField(blank=True, upload_to="seo/")),
                ("canonical_url", models.URLField(blank=True)),
                ("schema_json", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SEO Settings",
                "verbose_name_plural": "SEO Settings",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("site_name", models.CharField(default="Aai Bhavani Consultant", max_length=200)),
                ("site_tagline", models.CharField(blank=True, max_length=300)),
                ("logo", models.ImageField(blank=True, upload_to="site/")),
                ("favicon", models.ImageField(blank=True, upload_to="site/")),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("google_map_url", models.URLField(blank=True)),
                ("working_hours", models.CharField(blank=True, max_length=200)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#C8973B", max_length=7)),
                ("secondary_color", models.CharField(default="#1A1A2E", max_length=7)),
                ("background_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("font_family", models.CharField(default="Inter", max_length=100)),
                ("border_radius", models.CharField(default="8px", max_length=20)),
                ("animation_speed", models.CharField(default="0.3s", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("open_new_tab", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="cms.navigationitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("page", models.CharField(default="home", max_length=100)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("stats", "Stats"),
                            ("services", "Services"),
                            ("about", "About Us"),
                            ("gallery", "Gallery"),
                            ("testimonials", "Testimonials"),
                            ("team", "Team"),
                            ("faq", "FAQ"),
                            ("contact", "Contact"),
                            ("referral", "Referral Program"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("desktop_settings", models.JSONField(blank=True, default=dict)),
                ("tablet_settings", models.JSONField(blank=True, default=dict)),
                ("mobile_settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("page", "section_type")},
            },
        ),
    ]
